spring:
  mail:
    host: smtp.mail.ru
    port: 465
    ssl:
      enabled: true
    username: ${USERNAME_MAIL}
    password: ${PASSWORD_MAIL}
  kafka:
    session:
      timeout:
        ms: 15000
    bootstrap-servers: localhost:9092
    consumer:
      group-id: task-status
    template:
      default-topic: task-status-topic
  flyway:
    enabled: true
    user: ${FLYWAY_USERNAME}
    password: ${FLYWAY_PASSWORD}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  application:
    name: open_school_t1
  jpa:
    hibernate:
      ddl-auto: update