spring:
  flyway:
    enabled: true
    user: ${FLYWAY_USERNAME}
    password: ${FLYWAY_PASSWORD}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  application:
    name: open_school_t1
  jpa:
    hibernate:
      ddl-auto: update